[package]
name = "flappy"
version = "0.0.1"
edition = "2021"
author = ["Patryk Hegenberg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
